#!/bin/sh
set -e

# Create default config if missing
if [ ! -f /etc/rbfeeder.ini ]; then
    echo "[client]" > /etc/rbfeeder.ini
    echo "network_mode=false" >> /etc/rbfeeder.ini
    echo "log_file=/var/log/rbfeeder.log" >> /etc/rbfeeder.ini
    echo "" >> /etc/rbfeeder.ini
    echo "[network]" >> /etc/rbfeeder.ini
    echo "mode=beast" >> /etc/rbfeeder.ini
    echo "external_port=30005" >> /etc/rbfeeder.ini
    echo "external_host=127.0.0.1" >> /etc/rbfeeder.ini
    echo "" >> /etc/rbfeeder.ini
fi

case "$1" in
   configure)
       # Create system user "rbfeeder" if it doesn't exist
       if ! id -u rbfeeder >/dev/null 2>&1; then
         adduser --system --group --home /nonexistent --no-create-home rbfeeder
       fi

       # Ensure user "rbfeeder" is in plugdev group
       adduser rbfeeder plugdev
    ;;
esac




#DEBHELPER#

exit 0
